version: '3.8'

services:
    web:
        build: .
        ports:
            - 5001:5000
        environment:
            - DATABASE_URL=postgresql://inventory-manager:inventory-password@db/inventory-manager
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:16.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=inventory-manager
            - POSTGRES_PASSWORD=inventory-password
            - POSTGRES_DB=inventory-manager
        healthcheck:
            test: 'pg_isready -U inventory-manager'
            interval: 1s
            timeout: 5s
            retries: 20

volumes:
    postgres_data:
